"""add unique event_id to activity_log

Revision ID: e0f1c0e20575
Revises: 1f1e0d02cf23
Create Date: 2026-06-23 14:57:02.068630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f1c0e20575'
down_revision: Union[str, Sequence[str], None] = '1f1e0d02cf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_log', sa.Column('event_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'activity_log', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_log', type_='unique')
    op.drop_column('activity_log', 'event_id')
    # ### end Alembic commands ###
